#!/usr/bin/perl
use 5.018;
use utf8;

use Cairo;
use Gtk2;

my $cairo_surface = Cairo::PdfSurface->create('card.pdf', 8.5*72, 11*72);
my $cr = Cairo::Context->create($cairo_surface);
$cr->translate(0.70 * 72, 0.75 * 72);

my $pb = Gtk2::Gdk::Pixbuf->new_from_file('/tmp/anthony.jpeg');
Gtk2::Gdk::Cairo::Context::set_source_pixbuf($cr, $pb, 0, 0);

my $scale = $pb->get_height / (72*1.125);
my $m = $cr->get_source->get_matrix;
$m->scale($scale, $scale);
$cr->get_source->set_matrix($m);

$cr->rectangle(0, 0, 3.5*72, 2*72);
$cr->fill;

$cr->set_source_rgb(0, 0, 0);
$cr->move_to(72, 0);
my $layout = Pango::Cairo::create_layout($cr);
Pango::Cairo::Context::set_resolution($layout->get_context, 72);
$layout->set_width(Pango->scale * (72*2.5 - 72*0.125));
$layout->set_text(q{John "S" Very Insanely Extra Long Full Name});
$layout->set_font_description(
	Pango::FontDescription->from_string('DejaVu Serif Bold 13'));
Pango::Cairo::show_layout($cr, $layout);

$cr->show_page;
