INSERT INTO public.streets(street_name) VALUES
	('Antioch Place'),
	('Backwater Drive'),
	('Bonfire Peach Terrace'),
	('Burning Branch Terrace'),
	('Cliff Haven Court'),
	('Colby Court'),
	('Hollow Mountain Place'),
	('Kenyon Court'),
	('Maple Hollow Court'),
	('Mountain Laurel Terrace'),
	('Northbrook Way'),
	('Rusty Blackhaw Square'),
	('Southern Magnolia Square'),
	('Southern Oaks Terrace'),
	('Sweet Birch Terrace'),
	('Tamarack Ridge Square'),
	('Vermont Maple Terrace'),
	('Wesleyan Court');

INSERT INTO public.street_aliases(street_alias, street_ref) VALUES 
	('Antioch Pl',(SELECT street_ref FROM public.streets WHERE street_name='Antioch Place')),
	('Backwater Dr',(SELECT street_ref FROM public.streets WHERE street_name='Backwater Drive')),
	('Bonfire Peach Ter',(SELECT street_ref FROM public.streets WHERE street_name='Bonfire Peach Terrace')),
	('Burning Branch Ter',(SELECT street_ref FROM public.streets WHERE street_name='Burning Branch Terrace')),
	('Cliff Haven Ct',(SELECT street_ref FROM public.streets WHERE street_name='Cliff Haven Court')),
	('Colby Ct',(SELECT street_ref FROM public.streets WHERE street_name='Colby Court')),
	('Hollow Mountain Pl',(SELECT street_ref FROM public.streets WHERE street_name='Hollow Mountain Place')),
	('Kenyon Ct',(SELECT street_ref FROM public.streets WHERE street_name='Kenyon Court')),
	('Maple Hollow Ct',(SELECT street_ref FROM public.streets WHERE street_name='Maple Hollow Court')),
	('Mountain Laurel Ter',(SELECT street_ref FROM public.streets WHERE street_name='Mountain Laurel Terrace')),
	('Northbrook Way',(SELECT street_ref FROM public.streets WHERE street_name='Northbrook Way')),
	('Rusty Blackhaw Sq',(SELECT street_ref FROM public.streets WHERE street_name='Rusty Blackhaw Square')),
	('Southern Magnolia Sq',(SELECT street_ref FROM public.streets WHERE street_name='Southern Magnolia Square')),
	('Southern Oaks Ter',(SELECT street_ref FROM public.streets WHERE street_name='Southern Oaks Terrace')),
	('Sweet Birch Ter',(SELECT street_ref FROM public.streets WHERE street_name='Sweet Birch Terrace')),
	('Tamarack Ridge Sq',(SELECT street_ref FROM public.streets WHERE street_name='Tamarack Ridge Square')),
	('Vermont Maple Ter',(SELECT street_ref FROM public.streets WHERE street_name='Vermont Maple Terrace')),
	('Wesleyan Ct',(SELECT street_ref FROM public.streets WHERE street_name='Wesleyan Court'));
