INSERT INTO public.streets VALUES
	('Sweet Birch Terrace'),
	('Vermont Maple Terrace'),
	('Rusty Blackhaw Square'),
	('Southern Oaks Terrace'),
	('Hollow Mountain Place'),
	('Maple Hollow Court'),
	('Cliff Haven Court'),
	('Backwater Drive'),
	('Northbrook Way'),
	('Tamarack Ridge Square'),
	('Bonfire Peach Terrace'),
	('Mountain Laurel Terrace'),
	('Burning Branch Terrace'),
	('Antioch Place'),
	('Wesleyan Court'),
	('Colby Court');

INSERT INTO public.street_aliases(street_alias, street_name) VALUES 
	('Sweet Birch Ter','Sweet Birch Terrace'),
	('Vermont Maple Ter','Vermont Maple Terrace'),
	('Rusty Blackhaw Sq','Rusty Blackhaw Square'),
	('Southern Oaks Ter','Southern Oaks Terrace'),
	('Hollow Mountain Pl','Hollow Mountain Place'),
	('Maple Hollow Ct','Maple Hollow Court'),
	('Cliff Haven Ct','Cliff Haven Court'),
	('Backwater Dr','Backwater Drive'),
	('Northbrook Way','Northbrook Way'),
	('Tamarack Ridge Sq','Tamarack Ridge Square'),
	('Bonfire Peach Ter','Bonfire Peach Terrace'),
	('Mountain Laurel Ter','Mountain Laurel Terrace'),
	('Burning Branch Ter','Burning Branch Terrace'),
	('Antioch Pl','Antioch Place'),
	('Wesleyan Ct','Wesleyan Court'),
	('Colby Ct','Colby Court');
