INSERT INTO public.streets VALUES
	('Antioch Place'),
	('Backwater Drive'),
	('Bonfire Peach Terrace'),
	('Burning Branch Terrace'),
	('Cliff Haven Court'),
	('Colby Court'),
	('Hollow Mountain Place'),
	('Maple Hollow Court'),
	('Mountain Laurel Terrace'),
	('Northbrook Way'),
	('Rusty Blackhaw Square'),
	('Southern Oaks Terrace'),
	('Sweet Birch Terrace'),
	('Tamarack Ridge Square'),
	('Vermont Maple Terrace'),
	('Wesleyan Court');

INSERT INTO public.street_aliases(street_alias, street_name) VALUES 
	('Antioch Pl','Antioch Place'),
	('Backwater Dr','Backwater Drive'),
	('Bonfire Peach Ter','Bonfire Peach Terrace'),
	('Burning Branch Ter','Burning Branch Terrace'),
	('Cliff Haven Ct','Cliff Haven Court'),
	('Colby Ct','Colby Court'),
	('Hollow Mountain Pl','Hollow Mountain Place'),
	('Maple Hollow Ct','Maple Hollow Court'),
	('Mountain Laurel Ter','Mountain Laurel Terrace'),
	('Northbrook Way','Northbrook Way'),
	('Rusty Blackhaw Sq','Rusty Blackhaw Square'),
	('Southern Oaks Ter','Southern Oaks Terrace'),
	('Sweet Birch Ter','Sweet Birch Terrace'),
	('Tamarack Ridge Sq','Tamarack Ridge Square'),
	('Vermont Maple Ter','Vermont Maple Terrace'),
	('Wesleyan Ct','Wesleyan Court');
